name: Terraform Deployment

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

  workflow_dispatch:

jobs:

  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_SSH_public_key: ${{ vars.SSH_PUBLIC_KEY_FOR_EC2 }}

    defaults:
      run: 
        working-directory: terraform

    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Terraform Initialization
        run: terraform init 

      - name: Terraform format
        run: terraform fmt

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        run: terraform apply -auto-approve

  deploy:
    runs-on: ubuntu-latest
      
    needs: terraform

    steps: 
      - name: placeholder
        run: echo "Deployment job will be implemented later"

  verify:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: placeholder
        run: echo "verify job will be implemented later"